### ISSUE TITLE
App Crashing on first launch.

### ISSUE THREAD

**Issue by amanyadav** [amanyadav/AndroidAppManager#1]
E/AndroidRuntime(10881): FATAL EXCEPTION: main
E/AndroidRuntime(10881): Process: com.cs2guru.appmanager, PID: 10881
E/AndroidRuntime(10881): java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1027)
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:664)
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:397)
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:905)
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
E/AndroidRuntime(10881):    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:136)
E/AndroidRuntime(10881):    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
E/AndroidRuntime(10881):    at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
E/AndroidRuntime(10881):    at com.cs2guru.appmanager.database.DatabaseHandler.getAllAppInfo(DatabaseHandler.java:164)
E/AndroidRuntime(10881): at com.cs2guru.appmanager.adapter.InstalledFragmentAdapter.getRowList(InstalledFragmentAdapter.java:39)
E/AndroidRuntime(10881):    at com.cs2guru.appmanager.adapter.InstalledFragmentAdapter.<init>(InstalledFragmentAdapter.java:34)
E/AndroidRuntime(10881):    at com.cs2guru.appmanager.fragments.InstalledFragment.onCreateView(InstalledFragment.java:23)

**Comment by amanyadav** [comment]
fixed
